### ISSUE TITLE
Just need some guidance on where to start troubleshooting. 

### ISSUE THREAD

**Issue by bhudlemeyer** [mkuratczyk/prometheus-on-PCF#3]
I followed the direction and have a running deployment but I can only see graphs and data for bosh. I can not see any CF related stats or mysql. 

After pulling in the dashboard templates manually (as they wouldn't auto pull in for some reason) I also see that Environment and Deployment are blank on all CF related dashboards.  I also had to manually pull in the bosh dashboards so not sure that manual pull has anything to do with it but figured I would throw it in there.

**Comment by benjaminguttmann-avtq** [comment]
Hi, perhaps the FAQ of the Bosh Exporter (have a look at the scrape configs) will help you with that: 

https://github.com/cloudfoundry-community/bosh_exporter/blob/master/FAQ.md

I don't know how big your environment is but perhaps the exporter got a timeout before the bosh task is executed. After successfully executing the bosh task once the deployment information should be added to the dashboards.

**Comment by bhudlemeyer** [comment]
This is what I saw when doing the deploy the first time.

Director task 2219
  Started preparing deployment > Preparing deployment. Done (00:00:02)

  Started preparing package compilation > Finding packages to compile. Done
(00:00:00)

  Started updating instance alertmanager >
alertmanager/332e5631-7295-42b3-a353-7e8d5b24864a (0) (canary)
  Started updating instance grafana >
grafana/81aeeeca-f236-4df1-9301-d99495081672 (0) (canary)
  Started updating instance nginx >
nginx/040d36eb-d2a3-44a4-8c59-bea67865d5fc (0) (canary)
  Started updating instance prometheus >
prometheus/388a3180-589b-4fa0-8da6-12cd1f938ca5 (0) (canary)
     Done updating instance nginx >
nginx/040d36eb-d2a3-44a4-8c59-bea67865d5fc (0) (canary) (00:00:24)
     Done updating instance alertmanager >
alertmanager/332e5631-7295-42b3-a353-7e8d5b24864a (0) (canary) (00:00:26)
   Failed updating instance grafana >
grafana/81aeeeca-f236-4df1-9301-d99495081672 (0) (canary): Action Failed
get_task: Task 8b2e133e-06b6-4977-4249-74640958827a result: 1 of 1
post-start scripts failed. Failed Jobs: grafana. (00:00:26)


The post-job is looking for the *.json and they aren't on the server.

Doing a re-deploy to change scrap settings I also just had all the
exporters fail to start.
 Failed updating instance prometheus >
prometheus/388a3180-589b-4fa0-8da6-12cd1f938ca5 (0) (canary): 'prometheus/0
(388a3180-589b-4fa0-8da6-12cd1f938ca5)' is not running after update. Review
logs for failed jobs: prometheus, blackbox_exporter, bosh_exporter,
cf_exporter, mysqld_exporter, firehose_exporter, collectd_exporter,
consul_exporter, github_exporter, graphite_exporter, haproxy_exporter,
nats_exporter, pushgateway, rabbitmq_exporter, redis_exporter,
statsd_exporter, node_exporter (00:01:12)

This is a very small lab deploy of PCF. Signle of everything but the
routers which I am load balancing through a pfsense router.

**Comment by mkuratczyk** [comment]
Oh, you probably ran into this: https://github.com/cloudfoundry-community/prometheus-boshrelease/pull/49

The PR was merged after 0.14 was released

**Comment by mkuratczyk** [comment]
No, sorry, actually the change this PR fixed also happened after 0.14. The problem I guess is that this sample manifest already relies on post-0.14 changes (globs). You need an older version of the manifest (before my last commit)

**Comment by bhudlemeyer** [comment]
I am using the latest release of promethus-boshrelease I believe so should have those globs?
I uploaded the release per instructions just yesterday from here:

bosh upload release https://bosh.io/d/github.com/cloudfoundry-community/prometheus-boshrelease

 prometheus                | 14.0.0*   | 95965f63+

But that is almost the exact message I am getting:
`grafana/81aeeeca-f236-4df1-9301-d99495081672:/var/vcap/jobs/grafana/bin# ./post-start
[Wed Apr 12 14:33:37 UTC 2017] Calling 'grafana-users' ...
[Wed Apr 12 14:33:37 UTC 2017] Calling 'prometheus-datasource' ...
{"id":1,"message":"Datasource updated","name":"prometheus"}
Updated datasource prometheus at Wed Apr 12 14:33:37 UTC 2017
[Wed Apr 12 14:33:37 UTC 2017] Calling 'prometheus-dashboards' ...
Updating dashboard /var/vcap/packages/bosh_dashboards/*.json at Wed Apr 12 14:33:37 UTC 2017
sed: can't read /var/vcap/packages/bosh_dashboards/*.json: No such file or directory
`

**Comment by mkuratczyk** [comment]
Unfortunately no. See my second comment and check https://github.com/cloudfoundry-community/prometheus-boshrelease/commits/master. Globs were added a week after 0.14 was released. My last commit here noted that this requires a version newer than 0.14 (I didn't know there would be no 0.15 for over a month)

**Comment by bhudlemeyer** [comment]
Ahh I didnt catch that crud. OK is there a way for me to work around this?

**Comment by mkuratczyk** [comment]
You can either build the current prometheus-boshrelease on your own (bosh create release --force --with-tarball) upload it and try again or take an older version of prometheus.yml from this repo (which simply lists all json files explicitly)

**Comment by bhudlemeyer** [comment]
Re-deploy seems to have at the very least brought all the dashboards in but still don't see any metrics for CF only bosh still.

**Comment by mkuratczyk** [comment]
Show me firehose exporter logs please

**Comment by bhudlemeyer** [comment]
Showing this over and over in log:
time="2017-04-12T17:23:09Z" level=error msg="Error while reading from the Firehose: Received a status code 401 Unauthorized" source="firehose_nozzle.go:104"
time="2017-04-12T17:24:09Z" level=error msg="Error getting oauth token: Received a status code 401 Unauthorized. Please check your Client ID and Secret." source="uaa_token_refresher.go:39"
time="2017-04-12T17:24:09Z" level=error msg="Error while reading from the Firehose: Received a status code 401 Unauthorized" source="firehose_nozzle.go:104"


client id I created. Used same password everywhere as this is just a lab. 
  prometheus-firehouse
    scope: uaa.none
    resource_ids: none
    authorized_grant_types: refresh_token client_credentials
    autoapprove:
    authorities: doppler.firehose
    name: prometheus-firehose
    lastmodified: 1491940723000

**Comment by bhudlemeyer** [comment]
I am dumb just saw my typo

**Comment by mkuratczyk** [comment]
I hope fixing the typo solved the problem so I'm closing this issue.
